name: silver_shimmer
description: >
  A customizable Flutter package for creating elegant shimmer loading effects. 
  Supports classic, wave, and pulse shimmer styles with flexible configuration options.
version: 0.0.8
homepage: https://github.com/advait-bhitkar/silver_shimmer
repository: https://github.com/advait-bhitkar/silver_shimmer

topics:
  - shimmer
  - loading
  - animation
  - ui
  - flutter-widget


environment:
  sdk: ^3.6.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

